#m3ss14s 17062024
version: '3'

services:
  pritunl:
    image: 'jippi/pritunl:latest'
    privileged: true
    ports:
      - '8990:80' #on lab alterado de 80 para 8990
      - '9443:443' #on lab alterado de 443 para 9443
      - '1194:1194/udp'
      - '1194:1194/tcp'
    volumes:
      - 'pritunl_data:/var/lib/pritunl'
      - 'pritunl_db:/var/lib/mongodb'

volumes:
  pritunl_data:
    driver: local
  pritunl_db:
    driver: local
#docker container exec -it d8d /bin/bash
#root@d8d387687324:/# pritunl default-password
